--- #YAML:1.0
name:               XML-IODEF
version:            0.07_3
abstract:           A module for building/parsing IODEF messages
author:
    - John Green johng@cpan.org, Wes Young <wes@barely3am.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:            ~
    XML::DOM:            ~
    XML::Parser:         ~
    XML::Parser::Expat:  ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
